// <auto-generated />
namespace BioscoopSysteemWebsite.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_31032015_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_31032015_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201503302315007_update_31032015_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
